### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by astropaul73** [jlmborges/VisAC#1]
I've tried installing the latest R4.2.2, tried R4.2.0, and tried R4.1.3 in case because that's what your editor showed in the video.
As shown on instructions pages I've done
>setwd("C:\VisAC") [where I have the three files mentioned and I unzipped it in case that was a thing.]
>install.packages("VisAC_1.0.zip")
>install.packages("VisAC_1.0")
I always get this error:
Warning in install.packages :
  package ‘VisAC_1.0’ is not available for this version of R

and so 
>library(VisAC) 
doesn't work, VisAC doesn't show up in the dropdown either. I'm assuming because of the above error it just isn't installing.

The instructions seem good, and I'm pretty sure i've done all the pre-reqs, R, RTools, RStudio, I can't get VisAC to load.  Wish I could, would like to see my .ged show some things.

**Comment by astropaul73** [comment]
I solved 
>install.packages("VisAC_1.0.zip")
by clicking the Packages tab, clicking +install button, selecting c:\VisAC\VisAC_1.0.zip and clicking install.  this showed:
package ‘VisAC’ successfully unpacked and MD5 sums checked

however, now, using R4.2.0, when typing
>library(VisAC) [VisAC now shows up in the prompt]
showed some errors about the required packages being for R4.2.2.
So I upgraded to R4.2.2, now for 
>library(VisAC) I'm getting:
Loading required package: ggforce
Loading required package: ggplot2
Loading required package: ggrepel
Loading required package: gtools
Loading required package: pedigree
Loading required package: Matrix
Error: package ‘pedigreeTools’ required by ‘VisAC’ could not be found

gonna keep trying.  R seems tricky to keep up with.

**Comment by jlmborges** [comment]
Dear Paul,

Thanks for your interest!

The package is not available in CRAN so you have to install it from the local file.

In my case I have to run the following instruction:

install.packages("C:/my_files/02_FEUP/03_Vis_Genealogy/VisAC_package/VisAC_1.0.zip", repos = NULL, type = "win.binary")

If you are using Rstudio you can do it from the menu "Tools/Install packages" and set the 'Install from:" option as seen in the figure below.

Hope this helps you.
Best regards,
Jose

**Comment by jlmborges** [comment]
Regarding the pedigreeTools package (https://github.com/Rpedigree/pedigreeTools) it seems that you have to install it from github. Please try the following:

#R functions related to pedigrees
install.packages(pkg='devtools',repos='https://cran.r-project.org/')  #1# install devtools
library(devtools)                                                                                   #2# load the library
install_git('https://github.com/Rpedigree/pedigreeTools/')                #3# install pedigreeTools from GitHub

**Comment by astropaul73** [comment]
I downloaded and installed the pedigreeTools.zip.gz from
https://cran.r-project.org/src/contrib/Archive/pedigreeTools/
>library(VisAC) finished ok

> VisAC()
Error in loadNamespace(x) : there is no package called ‘DT’

so I did >install.packages('DT') [so this should probably be in required_packages.R also. doing at the command line worked for me though anyway]
>install.packages("tidyrules") [is also needed, or it will crash later.
now >VisAC() works! 
hope the above can help anyone coming after me having the same problem.

**Comment by astropaul73** [comment]
very cool visualization! I got my own gedcom to load and work. showing 9 generations for one particular gr-grandmother I have, descended from tons of New England Great Migration ancestors.  It's very cool to see more clearly the common ancestors.  One thing that would be cool - if the yellow labels stating the relationship included all the relationships (ex. my gr. grandmother, the yellow label for her parents is saying "2 x 5th cousin" - which is cool it's picking up the 5th cousin two ways, but, they're also 5th cousin 1R, and 6th cousin, and 6th cousin 1R, and 7th cousin. Any chance the Yellow label could list all those?
In any case, this is very cool. A little tricky getting to work in R, but, worth it and very cool.
